source 'git@git.pixio.com:pixio-libraries/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'PXPinnedRotation' do
  pod "PXPinnedRotation", :path => "../"
end

target 'Tests' do
  pod "PXPinnedRotation", :path => "../"
end
